### ISSUE TITLE
Bigger export resolution

### ISSUE THREAD

**Issue by AndreaCioccarelli** [TheAndroidMaster/ScreenshotMaker#6]
Shouldn't be a higer resolution export a good option?
On a device with a good display the image is a little bit chunky, do you think it's possible to make it bigger?

**Comment by TheAndroidMaster** [comment]
Yeah, I was planning on adding more options eventually. I'm a little busy with other projects right now, but it's pretty easy to change if you want to change it yourself and make a PR, I'm pretty sure the resolutions are just defined in an array somewhere. If not, I should have it done next week sometime.

**Comment by TheAndroidMaster** [comment]
Okay, maybe not this week. I got distracted. Next week it is. Probably.
